// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FlutterBoook.Models
{
    public partial class Appointment
    {
        [StringLength(100)]
        public string Event { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [Key]
        [Column("time")]
        public TimeSpan Time { get; set; }
        [Column("Event_Details")]
        [StringLength(50)]
        public string EventDetails { get; set; }
    }
}