// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FlutterBoook.Models
{
    public partial class Contact
    {
        [StringLength(50)]
        public string Name { get; set; }
        [Key]
        public int Number { get; set; }
        [Column("Img_Url")]
        [StringLength(100)]
        public string ImgUrl { get; set; }
    }
}