// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FlutterBoook.Models
{
    public partial class Note
    {
        [Key]
        [Column("Note_Title")]
        [StringLength(20)]
        public string NoteTitle { get; set; }
        [Column("Note_Details")]
        public string NoteDetails { get; set; }
    }
}