// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FlutterBoook.Models
{
    public partial class Task
    {
        [Key]
        [Column("Task_Title")]
        [StringLength(50)]
        public string TaskTitle { get; set; }
        [Column("Task_Details")]
        [StringLength(50)]
        public string TaskDetails { get; set; }
    }
}