// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FlutterBoook.Models;

#nullable disable

namespace FlutterBoook.Data
{
    public partial class FlutterbookContext : DbContext
    {
        public FlutterbookContext()
        {
        }

        public FlutterbookContext(DbContextOptions<FlutterbookContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Task> Task { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Arabic_100_CI_AI");

            modelBuilder.Entity<Appointment>(entity =>
            {
                entity.Property(e => e.Event).IsUnicode(false);

                entity.Property(e => e.EventDetails).IsUnicode(false);
            });

            modelBuilder.Entity<Contact>(entity =>
            {
                entity.Property(e => e.Number).ValueGeneratedNever();

                entity.Property(e => e.ImgUrl).IsUnicode(false);

                entity.Property(e => e.Name).IsUnicode(false);
            });

            modelBuilder.Entity<Note>(entity =>
            {
                entity.Property(e => e.NoteTitle).IsUnicode(false);

                entity.Property(e => e.NoteDetails).IsUnicode(false);
            });

            modelBuilder.Entity<Task>(entity =>
            {
                entity.Property(e => e.TaskTitle).IsUnicode(false);

                entity.Property(e => e.TaskDetails).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}